INSERT INTO RESERVATIONS(ADDRESS, EMAIL,  START_BOOKING_TIME, END_BOOKING_TIME, NUMBER_OF_PEOPLE, SURNAME, TABLE_NUMBER, PHONE_NUMBER)
VALUES ('Riga 123', 'Riga_123@gmail.com', current_timestamp(0), timestampadd(HOUR, 2, current_timestamp(0)), 3, 'Vilks',7, '+371 235436567');

INSERT INTO RESERVATIONS(ADDRESS, EMAIL,  START_BOOKING_TIME, END_BOOKING_TIME, NUMBER_OF_PEOPLE, SURNAME, TABLE_NUMBER, PHONE_NUMBER)
VALUES ('Pikk 5', 'pv@gmail.com', CURRENT_TIMESTAMP, TIMESTAMPADD (HOUR, 2, CURRENT_TIMESTAMP), 5, 'Veelaid', 5,' +372 5555 5555');

INSERT INTO RESERVATIONS(ADDRESS, EMAIL,  START_BOOKING_TIME, END_BOOKING_TIME, NUMBER_OF_PEOPLE, SURNAME, TABLE_NUMBER, PHONE_NUMBER)
VALUES ('Pikk 18', 'pva@gmail.com', CURRENT_TIMESTAMP, TIMESTAMPADD (HOUR, 2, CURRENT_TIMESTAMP), 5, 'Vabarna', 6,' +372 5555 5556');

INSERT INTO RESERVATIONS(ADDRESS, EMAIL,  START_BOOKING_TIME, END_BOOKING_TIME, NUMBER_OF_PEOPLE, SURNAME, TABLE_NUMBER, PHONE_NUMBER)
VALUES ('Pikk 23', 'peeter741@gmail.com', CURRENT_TIMESTAMP, TIMESTAMPADD (HOUR, 2, CURRENT_TIMESTAMP), 5, 'Lastik', 10,' +372 5555 5557');

INSERT INTO RESERVATIONS(ADDRESS, EMAIL,  START_BOOKING_TIME, END_BOOKING_TIME, NUMBER_OF_PEOPLE, SURNAME, TABLE_NUMBER, PHONE_NUMBER)
VALUES ('Marszałkowska 5', 'mpastuszka@gmail.com', CURRENT_TIMESTAMP, TIMESTAMPADD(HOUR,2,CURRENT_TIMESTAMP), 5, 'Pastuszka', 11, '+48 555 543 123');

INSERT INTO RESERVATIONS(ADDRESS, EMAIL,  START_BOOKING_TIME, END_BOOKING_TIME, NUMBER_OF_PEOPLE, SURNAME, TABLE_NUMBER, PHONE_NUMBER)
VALUES ('Marszałkowska 5', 's.khanimirzaee@gmail.com', CURRENT_TIMESTAMP, TIMESTAMPADD(HOUR,2,CURRENT_TIMESTAMP), 5, 'Samaneh', 1, '+48 555 321 123');

INSERT INTO RESERVATIONS(ADDRESS, EMAIL,  START_BOOKING_TIME, END_BOOKING_TIME, NUMBER_OF_PEOPLE, SURNAME, TABLE_NUMBER, PHONE_NUMBER)
VALUES ('Marszałkowska 5', 'sami_khani@gmail.com', CURRENT_TIMESTAMP, TIMESTAMPADD(HOUR,2,CURRENT_TIMESTAMP), 5, 'Sami', 4, '+48 555 543 456');
